[webserver]
port = ":9090"              # port to bind the web server to. defaults ":8080"

	[webserver.headers]
	Access-Control-Allow-Origin = "*"
	Cache-Control = "no-cache, no-store, must-revalidate"

[cache]                     # configure a tile cache
type = "file"               # a file cache will cache to the local file system
basepath = "/tmp/tegola"    # where to write the file cache

# register data providers
[[providers]]
name = "tl"       # provider name is referenced from map layers (required)
type = "postgis"            # the type of data provider. currently only supports postgis (required)
host = "localhost"          # postgis database host (required)
port = 1234                 # postgis database port (required)
database = "${PGDATABASE}"         # postgis database name (required)
user = "${PGUSER}"             # postgis database user (required)
password = "${PGPASSWORD}"                # postgis database password (required)
srid = 4326                 # The default srid for this provider. Defaults to WebMercator (3857) (optional)
max_connections = 50        # The max connections to maintain in the connection pool. Default is 100. (optional)
# ssl_mode = "prefer"        # PostgreSQL SSL mode*. Default is "disable". (optional)

	#[[providers.layers]]
	#name = "active_stops"           
	#tablename = "active_stops" 
	#geometry_fieldname = "geometry"   
    #geometry_type = "point"
	#id_fieldname = "id"               
	#srid = 4326                       
	#sql = "SELECT id, ST_AsBinary(geometry) AS geometry FROM active_stops WHERE geometry && !BBOX!"

    [[providers.layers]]
    name = "active_routes"
	geometry_fieldname = "geometry"  
    geometry_type = "linestring"
	id_fieldname = "id"   
	srid = 4326           
	sql = "SELECT id, ST_AsBinary(geometry) AS geometry FROM active_routes WHERE geometry && !BBOX!"

# maps are made up of layers
[[maps]]
name = "tl"                           
	#[[maps.layers]]
	#name = "active_stops"                         
	#provider_layer = "tl.active_stops"  
	#min_zoom = 0                           
	#max_zoom = 30                          
	[[maps.layers]]
	name = "active_routes"                              
	provider_layer = "tl.active_routes"  
	min_zoom = 0                       
	max_zoom = 8                   

