name: Publish
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run build
      env:
        GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
        GRAPHQL_APIKEY: ${{ secrets.GRAPHQL_APIKEY }}
        TILE_APIKEY: ${{ secrets.TILE_APIKEY }}
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -U awscli
    - run: aws s3 sync dist s3://www-transit-land-v2/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
